[workspace]
members = [
    "rust/crates/pricing",
    "rust/crates/indicator",
    "rust/crates/pyfinance",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Fulong Tan"]
license = "MIT OR Apache-2.0"

[workspace.dependencies]
thiserror = "1.0"
